### ISSUE TITLE
Type Blob can't edit directly with SQL

### ISSUE THREAD

**Issue by clavat** [Spomky-Labs/IpFilterBundle#6]
Hello, i found your bundle after long time search, it's the only one do ip filters ?
I installed your bundle, and it works very fine but how it's possible to edit ip blacklisted without any PHP execution ?
I got phpmyadmin, i seen the type of ip is Blob, and i can't edit it directly with the panel. phpmyadmin ask me to upload binarie file. I can create this file with text editor like notepadd ?

Or it's possible to add the possibility to choose the type of column IP/IPRange on databases with config file ?

Thanks for help.

**Comment by Spomky** [comment]
Hi,

You can not edit blacklisted IP addresses because because they are stored in binary.
It is the quicklyest way to list and compare IP addresses.

IMO, the best way to edit those addresses is to create a script or console command.

**Comment by Spomky** [comment]
I updated the way I store IP addresses in database.
The IPs stored are now in text, but you will see the hex representation (`192.168.1.1` => `000000000000000000000000C0A80101`).

You can try using the new `v2.0.x` branch:
```sh
composer require "spomky-labs/ip-filter-bundle" "2.0.*@dev"
```

Be carefull, I changed the intefaces, managers, entities and configuration of the bundle (should be better for developpers now).
